### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by shiruizhao** [pluveto/Mathink#2]
Hi,
Great work! I tried it on Centos 7. It didn't work. which seems like GUI.exe cannot run on linux. Do you have any plan to develop a linux version?
Error log:
'''
/FI: TASKLIST: command not found
Traceback (most recent call last):
  File "mathink.py", line 78, in <module>
    if not process_exists("Mathink.GUI.exe"):
  File "mathink.py", line 19, in process_exists
    output = subprocess.check_output(call, shell=True)
  File "/users/micas/szhao/no_backup/software/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/users/micas/szhao/no_backup/software/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('TASKLIST', '/FI', 'imagename eq Mathink.GUI.exe')' returned non-zero exit status 127.
'''

**Comment by pluveto** [comment]
For linux, we can use `ps -el` for check if a process is running, and we also need a GUI program to edit expression and generate svg file for this plugin to load. Pull request welcome.

**Comment by AhmedAbouhussein** [comment]
I am assuming there is no current support for linux then?

**Comment by pluveto** [comment]
> I am assuming there is no current support for linux then?

Sure. I'm sorry but I haven't learned how to develop GUI program for Linux
