### ISSUE TITLE
Trouble installing, getting the following error:

### ISSUE THREAD

**Issue by jsilve24** [pluveto/Mathink#7]
Thanks for putting this together. Unfortunately, I am having trouble getting it to work. 

I am using Inkscape version 1.0.2
Just following install instructions and using update v1.1 of this extension. 

The error occurs when I go to Extensions > Mathink... and try to press `apply`. 

```
/FI: 1: TASKLIST: not found
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/***/.config/inkscape/extensions/mathink.py", line 78, in <module>
    if not process_exists("Mathink.GUI.exe"):
  File "/home/***/.config/inkscape/extensions/mathink.py", line 19, in process_exists
    output = subprocess.check_output(call, shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('TASKLIST', '/FI', 'imagename eq Mathink.GUI.exe')' returned non-zero exit status 127.
```

Thank you!

**Comment by pluveto** [comment]
Sorry, only Windows supported
